; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
description                 = Provide ESP32 based devices with firmware
src_dir                     = src

[common]
extra_scripts               = ${esp_defaults.extra_scripts}

[scripts_defaults]
extra_scripts               = pre:pio-tools/pre_source_dir.py
                              pre:pio-tools/set_partition_table.py
                              pre:pio-tools/override_copy.py
#                              pre:pio-tools/compress-html.py
                              post:pio-tools/strip-flags.py

[esp_defaults]
extra_scripts               = post:pio-tools/name-firmware.py
                              post:pio-tools/gzip-firmware.py
#                              post:pio-tools/metrics-firmware.py
                              post:pio-tools/custom_target.py
                              ${scripts_defaults.extra_scripts}

[env]
platform = espressif32
framework = arduino
extra_scripts = ${esp_defaults.extra_scripts}
lib_deps =
#  file://./src/libraries/SeeedStudio_TFT_eSPI
#  file://./src/libraries/Seeed_Arduino_RoundDisplay
#  file://./src/libraries/SeeedStudio_lvgl
#  https://github.com/Seeed-Studio/Seeed_Arduino_RoundDisplay.git
  https://github.com/Seeed-Projects/SeeedStudio_lvgl.git#500a480c480ebd34465d93247b6d3156aa5aa824
  https://github.com/Seeed-Projects/SeeedStudio_TFT_eSPI.git#096f2fa3549475af17f5266f0200ea241e14151f
  bitbank2/AnimatedGIF@^2.1.1
  
build_flags =
   -D LV_CONF_PATH="${PROJECT_LIBDEPS_DIR}/${PIOENV}/lvgl/lv_conf.h"
#  -D USER_SETUP_LOADED=1
#  -include $PROJECT_LIBDEPS_DIR/$PIOENV/TFT_eSPI/User_Setups/Setup66_Seeed_XIAO_Round.h

[env:app_seeed_xiao_esp32c3-seeed_touch_104030087]
board = seeed_xiao_esp32c3

[env:app_seeed_xiao_esp32s3-seeed_touch_104030087]
board = seeed_xiao_esp32s3

[env:seeed_xiao_esp32s3-seeed_touch_104030087]
platform = espressif32
board = seeed_xiao_esp32s3