; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
description                 = Provide ESP32 based devices with firmware
src_dir                     = src
boards_dir                  = boards
build_cache_dir             = .cache
extra_configs               = platformio_env32.ini

[common]
extra_scripts               = ${esp_defaults.extra_scripts}
framework                   = arduino
board_build.filesystem      = littlefs
board_build.variants_dir    = variants/app
custom_unpack_dir           = unpacked_littlefs
monitor_speed               = 115200
monitor_echo                = yes
; *** Upload Serial reset method for Wemos and NodeMCU
upload_resetmethod          = nodemcu
check_skip_packages         = yes
lib_ldf_mode                = chain
lib_compat_mode             = strict


[app]
; Uncomment if you do NOT want gzipped map file(s)
;disable_map_gz = 1
; Uncomment and specify a folder where to place the map file(s) (default set to folder build_output)
;map_dir = /tmp/map_files/
; Uncomment if you do NOT want additionally gzipped firmware file(s) at all
;disable_bin_gz = 1
; Uncomment if you want additionally gzipped esp32x firmware file(s)
;enable_esp32_gz = 1
; Uncomment and specify a folder where to place the firmware file(s) (default set to folder build_output)
;bin_dir = /tmp/bin_files/
; Global build flags (used for all env) can be overridden in "platformio_override.ini"
build_unflags               =
build_flags                 =


[scripts_defaults]
extra_scripts               = pre:pio-tools/pre_source_dir.py
                              pre:pio-tools/set_partition_table.py
                              pre:pio-tools/override_copy.py
#                              pre:pio-tools/compress-html.py
                              post:pio-tools/strip-flags.py

[esp_defaults]
extra_scripts               = post:pio-tools/name-firmware.py
                              post:pio-tools/gzip-firmware.py
#                              post:pio-tools/metrics-firmware.py
                              post:pio-tools/custom_target.py
                              ${scripts_defaults.extra_scripts}
; *** remove undesired all warnings
build_unflags               = ${app.build_unflags}
                               -Wall
;                              -mtarget-align
                              -Wdeprecated-declarations
build_flags                 = ${app.build_flags}
                              -DCORE_DEBUG_LEVEL=0
                              -Wl,-Map,firmware.map
                              -Wno-deprecated-declarations
;                              -mno-target-align
                              -mtarget-align
                              -free
                              -fipa-pta
                              -Wreturn-type
                              -DTASMOTA  ; flag indicating that we are compiling Tasmota
; *********************************************************************
; *** Use custom settings from file user_config_override.h
                              -DUSE_CONFIG_OVERRIDE
; *********************************************************************

[env]
platform = espressif32 @ 6.9.0
framework = arduino
extra_scripts = ${esp_defaults.extra_scripts}
lib_deps =
#  file://./src/libraries/SeeedStudio_TFT_eSPI
#  file://./src/libraries/Seeed_Arduino_RoundDisplay
#  file://./src/libraries/SeeedStudio_lvgl
#  https://github.com/Seeed-Studio/Seeed_Arduino_RoundDisplay.git
  https://github.com/Seeed-Projects/SeeedStudio_lvgl.git#500a480c480ebd34465d93247b6d3156aa5aa824
  https://github.com/Seeed-Projects/SeeedStudio_TFT_eSPI.git#096f2fa3549475af17f5266f0200ea241e14151f
  bitbank2/AnimatedGIF@^2.1.1
  
build_flags =
   -D LV_CONF_PATH="${PROJECT_LIBDEPS_DIR}/${PIOENV}/lvgl/lv_conf.h"
#  -D USER_SETUP_LOADED=1
#  -include $PROJECT_LIBDEPS_DIR/$PIOENV/TFT_eSPI/User_Setups/Setup66_Seeed_XIAO_Round.h

[esp82xx_defaults]
extra_scripts               = ${esp_defaults.extra_scripts}
build_flags                 = ${esp_defaults.build_flags}
                              -DNDEBUG
                              -DFP_IN_IROM
                              -DBEARSSL_SSL_BASIC
                              ; NONOSDK22x_190703 = 2.2.2-dev(38a443e)
                              -DPIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_190703
                              -DPIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH_LOW_FLASH
                              ; -DPIO_FRAMEWORK_ARDUINO_LWIP2_IPV6_HIGHER_BANDWIDTH -DUSE_IPV6 ; enables IPv6
                              ; VTABLES in Flash
                              -DVTABLES_IN_FLASH
                              ; remove the 4-bytes alignment for PSTR()
                              -DPSTR_ALIGN=1
                              ; restrict to minimal mime-types
                              -DMIMETYPE_MINIMAL
                              ; uncomment the following to enable TLS with 4096 RSA certificates
                              ;-DUSE_4K_RSA
lib_ignore                  =
                              ESP8266LLMNR
                              ESP8266NetBIOS
                              ESP8266SSDP
                              ESP8266WiFiMesh
                              GDBStub
                              ESP8266HTTPUpdateServer
                              SPISlave
                              Hash
; Disable next if you want to use ArduinoOTA in Tasmota (default disabled)
                              ArduinoOTA

[core]
; *** Esp8266 Tasmota modified Arduino core based on core 2.7.4. Added Backport for PWM selection
;platform                    = https://github.com/tasmota/platform-espressif8266/releases/download/2024.09.00/platform-espressif8266.zip
platform_packages           =
build_unflags               = ${esp_defaults.build_unflags}
build_flags                 = ${esp82xx_defaults.build_flags}
; *** Use ONE of the two PWM variants. Tasmota default is Locked PWM
                              ;-DWAVEFORM_LOCKED_PHASE
                              -DWAVEFORM_LOCKED_PWM
