name: Build CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
    paths:
      - '**.c'
      - '**.cpp'
      - '**.be'
      - '**.h'
      - '**.hpp'
      - '**.ino'
      - '**.json'
      - '**.properties'
      - 'pio-tools/*.py'
      - '**.ini'
      - '.github/workflows/build_all_the_things.yml'

jobs:
  base-images:
    runs-on: ubuntu-latest
    if: github.repository == 'printminion/seeedstudio-xiao-TFT_eSPI_GifPlayer_With_Touch'
    strategy:
      fail-fast: true
      matrix:
        variant:
          - app_seeed_xiao_esp32c3-seeed_touch_104030087
          - app_seeed_xiao_esp32s3-seeed_touch_104030087
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install wheel
          #python -m pip install --upgrade pip
          pip install -U platformio
          #platformio upgrade --dev
          #platformio update

      - name: Run PlatformIO
        run: platformio run -e ${{ matrix.variant }}

      - uses: jason2866/upload-artifact@v2.0.3
        with:
          name: firmware ${{ matrix.variant }}
          path: ./build_output
