name: Build CI

env:
  SOURCE_REPO: printminion/seeedstudio-xiao-TFT_eSPI_GifPlayer_With_Touch

on:
  workflow_dispatch:
  pull_request:
    branches: development
    paths:
      - '**.c'
      - '**.cpp'
      - '**.be'
      - '**.h'
      - '**.hpp'
      - '**.ino'
      - '**.json'
      - '**.properties'
      - 'pio-tools/*.py'
      - '**.ini'
      - '.github/workflows/build_all_the_things.yml'

jobs:
  os-check-win:
    runs-on: windows-2019
    if: github.repository == 'printminion/seeedstudio-xiao-TFT_eSPI_GifPlayer_With_Touch'
    strategy:
      fail-fast: true
      matrix:
        variant:
          - tasmota32-webcam
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install wheel
          #python -m pip install --upgrade pip
          pip install -U platformio
          #platformio upgrade --dev
          #platformio update
      - name: Run PlatformIO
        run: platformio run -e ${{ matrix.variant }}
      - uses: jason2866/upload-artifact@v2.0.3
        with:
          name: firmware
          path: ./build_output

  os-check-mac:
    runs-on: macos-14
    if: github.repository == 'printminion/seeedstudio-xiao-TFT_eSPI_GifPlayer_With_Touch'
    strategy:
      fail-fast: true
      matrix:
        variant:
          - tasmota32solo1-safeboot
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install wheel
          #python -m pip install --upgrade pip
          pip install -U platformio
          #platformio upgrade --dev
          #platformio update
      - name: Run PlatformIO
        run: platformio run -e ${{ matrix.variant }}
      - uses: jason2866/upload-artifact@v2.0.3
        with:
          name: firmware
          path: ./build_output

  base-images:
    runs-on: ubuntu-latest
    if: github.repository == 'printminion/seeedstudio-xiao-TFT_eSPI_GifPlayer_With_Touch'
    strategy:
      fail-fast: true
      matrix:
        variant:
          - tasmota32
          - tasmota32c6
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install wheel
          #python -m pip install --upgrade pip
          pip install -U platformio
          #platformio upgrade --dev
          #platformio update
          cp ./platformio_override_sample.ini ./platformio_override.ini
      - name: Run PlatformIO
        run: platformio run -e ${{ matrix.variant }}
      - uses: jason2866/upload-artifact@v2.0.3
        with:
          name: firmware
          path: ./build_output

  language-images:
    runs-on: ubuntu-latest
    if: github.repository == 'printminion/seeedstudio-xiao-TFT_eSPI_GifPlayer_With_Touch'
    strategy:
      fail-fast: true
      matrix:
        variant: [ tasmota ]
        language: [ EN ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install wheel
          #python -m pip install --upgrade pip
          pip install -U platformio
          #platformio upgrade --dev
          #platformio update
      - name: Run PlatformIO
        run: platformio run -e ${{ matrix.variant }}-${{ matrix.language }}
      - uses: jason2866/upload-artifact@v2.0.3
        with:
          name: firmware
          path: ./build_output
